
cover:
	HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,local,+ignore,^t/,+ignore,^xt/" prove -lr t
	cover

test-all:
	TEST_ALL=1 prove -lrv t

test:
	prove -lrv t

# YAML_PP_TRACE=1 YAML_TEST_DIR=M9B4 prove -lrv t

