test-suite:
	git branch test-suite --track origin/test-suite
	git worktree add test-suite test-suite

cover:
	HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,local,+ignore,^t/,+ignore,^xt/" prove -lr t
	cover

test-all:
	TEST_ALL=1 prove -lr t

test-all-verbose:
	TEST_ALL=1 prove -lrv t

test-valid-all:
	TEST_ALL=1 prove -lrv t/10.parse-valid.t

test-invalid-all:
	TEST_ALL=1 prove -lrv t/11.parse-invalid.t

test:
	prove -lr t

testp:
	prove -lr -j9 t

testv:
	prove -lrv t

# YAML_PP_TRACE=1 YAML_TEST_DIR=M9B4 prove -lrv t

gh-pages:
	git worktree add gh-pages gh-pages

gh-pages-status: gh-pages
	cd gh-pages && git status

gh-pages-diff: gh-pages
	cd gh-pages && git diff

gh-pages-commit: gh-pages
	cd gh-pages && git add . && git commit -m "Generate HTML"

gh-pages-push: gh-pages
	cd gh-pages && git push

test-suite-html: gh-pages
	perl etc/test-suite-html.pl > gh-pages/test-suite.html

grammar:
	perl etc/generate-grammar.pl

gen_examples:
	perl etc/generate-examples.pl

